apiVersion: v2
name: nrts-prc-api
description: Helm chart for deploying NRTS PRC API with scheduled update-shapes CronJob
type: application
version: 1.0.0
appVersion: '1.0.0'
keywords:
  - api
  - mongodb
  - nrts
  - prc
maintainers:
  - name: BCGOV
home: https://github.com/bcgov/nr-acrfd-comments
sources:
  - https://github.com/bcgov/nr-acrfd-comments
