# Secret is expected to be created externally before Helm deployment
# Create it with the following command in your namespace:
#
# oc create secret generic mongodb-secret \
#   -n <namespace> \
#   --from-literal=mongodb-username=<username> \
#   --from-literal=mongodb-password=<password> \
#   --from-literal=mongodb-database=<database> \
#   --from-literal=mongodb-admin-password=<admin-password>
#
# For example (DEV):
# oc create secret generic mongodb-secret -n 86cabb-dev \
#   --from-literal=mongodb-username=user54L \
#   --from-literal=mongodb-password=<dev-password> \
#   --from-literal=mongodb-database=prc-dev \
#   --from-literal=mongodb-admin-password=<dev-admin-password>
