{{- if and .Values.global.secrets .Values.global.secrets.enabled }}
{{- $mongodbSecret := (lookup "v1" "Secret" .Release.Namespace "mongodb-secret") }}
{{- if $mongodbSecret }}
{{- $mongodbData := $mongodbSecret.data }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend
  labels: {{- include "labels" . | nindent 4 }}
  {{- if .Values.global.secrets.persist }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
type: Opaque
data:
  MONGODB_USERNAME: {{ index $mongodbData "mongodb-username" }}
  MONGODB_PASSWORD: {{ index $mongodbData "mongodb-password" }}
  MONGODB_DATABASE: {{ index $mongodbData "mongodb-database" }}
{{- else }}
# NOTE: Secret 'mongodb-secret' not found in namespace '{{ .Release.Namespace }}'. Backend secret will not be created.
{{- end }}
{{- end }}
